### ISSUE TITLE
Can't set current line to bold or change textStyle is there any way to do so ?

### ISSUE THREAD

**Issue by ronaksuchak** [Lauzy/LyricView#2]
i want to change current line's textStyle to bold is there any way to do so ? needed help ASAP thank you in advance

**Comment by Lauzy** [comment]
I'm sorry I didn't see it in time because I was too busy. I've added several new attributes to support the feature you need. Hope help.
1. isLrcCurrentTextBold: current line bold
2. isLrcIndicatorTextBold: line indicated bold
